# Generated by Django 5.2.4 on 2025-07-17 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbeiro',
            name='horario_fim_almoco',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='horario_fim_trabalho',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='horario_inicio_almoco',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='horario_inicio_trabalho',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
