# Generated by Django 5.2.4 on 2025-07-17 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_barbeiro_horario_fim_almoco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDeFolga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='O dia específico da folga.')),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_de_folga', to='core.barbeiro')),
            ],
            options={
                'unique_together': {('barbeiro', 'data')},
            },
        ),
    ]
