# Generated by Django 5.2.4 on 2025-07-17 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_diadefolga'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioDeAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='O dia do bloqueio.')),
                ('hora_inicio', models.TimeField(help_text='Horário de início do bloqueio.')),
                ('hora_fim', models.TimeField(help_text='Horário de fim do bloqueio.')),
                ('motivo', models.CharField(blank=True, help_text='Motivo da ausência (opcional).', max_length=200, null=True)),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='core.barbeiro')),
            ],
            options={
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.DeleteModel(
            name='DiaDeFolga',
        ),
    ]
